apiVersion: v1
kind: Pod
metadata:
  name: some-test-pod
  namespace: apps
spec:
  containers:
  - name: container
    image: busybox
    command: ["sleep"]
    args: ["3600"]
  restartPolicy: OnFailure
