---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cert-injector-webhook
  name: cert-injector-webhook
  namespace: cert-injector
spec:
  type: ClusterIP
  ports:
    - port: 443
      protocol: TCP
      targetPort: 443
  selector:
    app: cert-injector-webhook
